### ISSUE TITLE
Gridview of each of PCs 

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#74]
#4

**Comment by hardik12** [comment]
creating a navigation for each Item - books, ebooks, pc and digital medias for gridview

**Comment by andyfengc** [comment]
Manage book:

BookListView.aspx

Manage pc:

PcListView.aspx

Manage Discs:

DiscListView.aspx

Manage Rooms:

RoomListView.aspx

**Comment by hardik12** [comment]
I lost all the progress done on this task due to unable to properly upload the progress back to the github repository. I will have to do it again.

**Comment by hardik12** [comment]
gridview created with database connectivity

**Comment by hardik12** [comment]
anyone adding a database connectivity should comment other user's  connection string in "webconfig" file and not delete.

then uncomment your connection string which is commented by other developer

this way we can use our connection string while keeping other's connection string as it is so that others can use their's while coding.
